export * from './studantRegister'
export * from './studantRegister.interface'
export * from './studantAddress'
export * from './financialAddress'
export * from './financial'
export * from './studantData'
export * from './studant'
export * from './studantPersonalData'
